sudo: required

language: python

services:
        - docker

before_install:
        - docker pull amadeuschan/osproject

script:
        - travis_wait "docker run -it amadeuschan/osproject /bin/sh -c ""git clone https://github.com/AmadeusChan/OS2018spring-projects-g10.git; cd OS2018spring-projects-g10/yggdrasil; make; python test_waldisk.py"""
        - echo "finished test_waldisk"
        - docker run -it amadeuschan/osproject /bin/sh -c "git clone https://github.com/AmadeusChan/OS2018spring-projects-g10.git; cd OS2018spring-projects-g10/yggdrasil; make; python test_xv6inode.py"
        - echo "finished test_xv6inode"
        - docker run -it amadeuschan/osproject /bin/sh -c "git clone https://github.com/AmadeusChan/OS2018spring-projects-g10.git; cd OS2018spring-projects-g10/yggdrasil; make; python test_bitmap.py"
        - echo "finished test_bitmap"
        - docker run -it amadeuschan/osproject /bin/sh -c "git clone https://github.com/AmadeusChan/OS2018spring-projects-g10.git; cd OS2018spring-projects-g10/yggdrasil; make; python test_inodepack.py"
        - echo "finished test_inodepack"
        - docker run -it amadeuschan/osproject /bin/sh -c "git clone https://github.com/AmadeusChan/OS2018spring-projects-g10.git; cd OS2018spring-projects-g10/yggdrasil; make; python test_partition.py"
        - echo "finished test_partition"


