sudo: required

language: python

services:
        - docker

before_install:
        - docker pull amadeuschan/osproject

script:
        - docker run -d amadeuschan/osproject /bin/sh -c "/root/OS2018spring-projects-g10; make verify"
        - docker ps -a
