sudo: required

language: python

services:
        - docker

before_install:
        - docker pull amadeuschan/osproject

script:
        - travis_wait 60 mvn docker run -t amadeuschan/osproject /bin/sh -c "git clone https://github.com/AmadeusChan/OS2018spring-projects-g10.git;cd OS2018spring-projects-g10/yggdrasil; make verify"
